### ISSUE TITLE
It is not recommeding properly.

### ISSUE THREAD

**Issue by Abhishekverma2002** [sametartann/Real-Estate-Agent#1]
I ran the program  but is not recommending the values. Can you share some testcases in here.

**Comment by sametartann** [comment]
You can find testcases in Main.java comment lines (lines from 72 to 255)

**Comment by Abhishekverma2002** [comment]
> You can find testcases in Main.java comment lines (lines from 72 to 255)

Thanks Buddy. 
I also want to be a part of this project . If you have any work in which I can contribute. Consider me in.
I know Core Java
